version: '2'
services:
  mongodb:
    image: mongo:latest
    hostname: "mongo.anunci.us"
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - './volumes/mongo/data/db:/data/db'
      - './volumes/mongo/data/config:/data/configdb'
    networks:
      backend:
        ipv4_address: 10.5.0.2
  redis:
    image: redis:3.2.6-alpine
    hostname: "redis.anunci.us"
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - './volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf'
      - './volumes/redis/data:/data'
    networks:
      backend:
        ipv4_address: 10.5.0.3
  tomcat:
    build: ./Dockerfile/tomcat
    container_name: tomcat
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -server -Xms48m -Xmx1024M -XX:MaxPermSize=512m
    ports:
      - '8080:8080'
    links:
      - mongodb:mongo.anunci.us
      - redis:redis.anunci.us
    restart: always
    networks:
      backend:
        ipv4_address: 10.5.0.4
  nginx:
    build: ./Dockerfile/nginx
    hostname : "nginx.anunci.us"
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - tomcat:web
    restart: always
    volumes:
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/config:/config
      - ./volumes/nginx/cache:/tmp/nginx_cache
      - ./volumes/nginx/logs:/nginx_logs
    networks:
      backend:
        ipv4_address: 10.5.0.5
  elasticsearch:
    image: "elasticsearch:2"
    container_name: elasticsearch
    command: "elasticsearch -Des.cluster.name='graylog'"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      backend:
        ipv4_address: 10.5.0.6
  graylog:
    image: graylog2/server:2.1.1-1
    container_name: graylog
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
    networks:
      backend:
        ipv4_address: 10.5.0.7
networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
