version: '2'
services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo/data:/data
  cache:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  tomcat:
    build: ./Dockerfile
    container_name: tomcat
    ports:
      - "8080:8080"
    links:
      - mongodb
      - cache
    restart: always
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./volumes/jenkins/jenkins:/jenkins
      #- ./volumes/jenkins/home:/var/jenkins_home
  elastic:
    image: "elasticsearch:latest"
    command: "elasticsearch -Des.cluster.name='graylog'"
    container_name: elastic
    volumes:
      - './volumes/graylog/data/elasticsearch:/usr/local/elastic'
    links:
      - mongodb:mongo
    ports:
      - "8084:8084"
  kibana:
    hostname: kibana:latest
    container_name: kibana
    domainname: locahost
    image: kibana
    links:
      - elastic:elasticsearch
    ports:
      - "80:8083"
      - "5601:5601"
