version: '2'
services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - './volumes/mongo/data:/data'
    networks:
      - back-tier
  cache:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - './volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf'
    networks:
      - back-tier
  tomcat:
    build: ./Dockerfile/tomcat
    container_name: tomcat
    ports:
      - "8080:8080"
    links:
      - mongodb
      - cache
    restart: always
    networks:
      - back-tier
  lighttpd:
    container_name: lighttpd
    build: ./Dockerfile/lighttpd
    volumes:
      - './volumes/lighttpd/static:/var/www/localhost/htdocs'
      - './volumes/lighttpd/config/lighttpd.conf:/etc/lighttpd/lighttpd2.conf'
    ports:
      - '80:80'
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
