version: '2'
services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - './volumes/mongo/data:/data'
    networks:
      - backend
  cache:
    image: redis:3.2.6-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - './volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf'
      - './volumes/redis/data:/data'
    networks:
      - backend
  web:
    build: ./Dockerfile/tomcat
    container_name: web
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -server -Xms48m -Xmx1024M -XX:MaxPermSize=512m
    ports:
      - '8080:8080'
    links:
      - mongodb:mongodb
      - cache:cache
    restart: always
    networks:
      - backend
  balancer:
    build: ./Dockerfile/nginx
    container_name: balancer
    ports:
      - '80:80'
      - '443:443'
    links:
      - web:web
    restart: always
    volumes:
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/config:/config
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
