version: '2'
services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - './volumes/mongo/data:/data'
  cache:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - './volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf'
  tomcat:
    build: ./Dockerfile
    container_name: tomcat
    ports:
      - "80:80"
    links:
      - mongodb
      - cache
    restart: always
