      #- ./volumes/jenkins/home:/var/jenkins_home
  elastic:
    image: "elasticsearch:latest"
    container_name: elastic
    volumes:
      - './volumes/logs:/usr/local/elasticsearch/data'
    links:
      - mongodb:mongo
    ports:
      - "8084:8084"
  kibana:
    hostname: kibana:latest
    container_name: kibana
    domainname: locahost
    image: kibana
    links:
      - elastic:elasticsearch
    ports:
      - "80:8083"
      - "5601:5601"
